### ISSUE TITLE
Unable to run in terminal

### ISSUE THREAD

**Issue by henck** [Armen138/night_terror#15]
I ran `npm install`. `npm start` fails due to module loading issues.

		$ npm start
		
		> night_terror@1.0.0 start D:\code\night_terror
		> node --experimental-modules terminal.js
		
		(node:7856) ExperimentalWarning: The ESM module loader is experimental.
		D:\code\night_terror\terminal.js:3
		import Game from './game/game.js';
		^^^^^^
		
		SyntaxError: Unexpected token import
		    at createScript (vm.js:80:10)
		    at Object.runInThisContext (vm.js:139:10)
		    at Module._compile (module.js:616:28)
		    at Object.Module._extensions..js (module.js:663:10)
		    at Module.load (module.js:565:32)
		    at tryModuleLoad (module.js:505:12)
		    at Function.Module._load (module.js:497:3)
		    at createDynamicModule (internal/loader/ModuleRequest.js:52:15)
		    at setExecutor (internal/loader/ModuleWrap.js:50:23)
		    at file:///D:/code/night_terror/terminal.js:11:5

**Comment by Armen138** [comment]
Most likely issue here is your version of NodeJS. Modern module imports require Node 12.* and above.
Check with
```
node --version
```

**Comment by henck** [comment]
You are right. I was running Node 8.3.1. I updated to the latest version by downloading the latest Windows installer and reinstalling. Ran `npm rebuild` for good measure. `npm run start` now works without issues.
